defaults:
  - override hydra/sweeper: "optuna"
  - override hydra/sweeper/sampler: "tpe"

hydra:
  sweeper:
    sampler:
      seed: 123
    direction: ["minimize", "maximize","maximize"]
    study_name: "lstm-big-sweep"
    storage: null
    n_trials: 2
    n_jobs: 1

    search_space:
      data_prep.clean_data.outlier_threshold:
        type: "float"
        low: 1.5
        high: 3.5
        step: 0.5
  
      modeling.data_loader.init.batch_size:
        type: "int"
        low: 128
        high: 512
        step: 128
      
      modeling.lstmae.model_params.hidden_size:
        type: "categorical"
        choices:
        - [[8, 4], [4, 8]]
        - [[32, 8], [8, 32]]
        - [[128, 16], [16, 128]]

data_prep:
  pipeline:
    input_dir: "/home/abb/data/input"         # Do not change        
    interim_dir: "/home/abb/data/interim"     # Do not change         
    processed_dir: "/home/abb/data/processed" # Do not change 
    conf_dir: "/home/abb/conf"                # Do not change            

  ingest_data:
    assets_dir: "assets"                      
    annotation_list: [
        "annotations/annotations_1.xlsx",
    ]
    time_col: "MEASUREMENT_TAKEN_ON(UTC)"
    cut_off_date: "01-7-21"
    asset_timezone: 0
    annotation_timezone: 8

  split_data:
    by: "asset"     # expects values "asset" or "time"
    test_size: 0.2
    random_state: 42
    follow_split: ""
    # follow_split: "/home/abb/data/processed/20220601_005850/split_data.json" # change timestamped folder if using a different split

  clean_data:
    features_to_standardize: [
        "Output Power",
        "Overall Vibration",
        "Peak to Peak (X)",
        "Peak to Peak (Y)",
        "Peak to Peak (Z)",
        "Skin Temperature",
        "Speed",
        "Motor Supply Frequency",
        "Vibration (Axial)",
        "Vibration (Radial)",
        "Vibration (Tangential)",
        "Acceleration RMS (Axial)",
        "Acceleration RMS (Radial)",
        "Acceleration RMS (Tangential)",
        "Bearing Condition"
    ]
    standardization_method: "RobustScaler"
    outlier_threshold: 99999
    outlier_window: 5
    nan_range_threshold: 48
    impute_nan_window: 48
    impute_nan_period: 1
    impute_nan_center: True
    bearing_cond_fill: -1
    convert_to_int: ["Bearing Condition", "Anomaly"]
    scaler_args:
      with_centering: True,      
      with_scaling: True,
      copy: True,
      quantile_range: [25.0, 75.0]
      unit_variance: False,
  feature_engineering:
    min_data_points: 24
    motor_supply_freq: "Motor Supply Frequency"
    
  inference_encoder:
    enc_name: "encoder"

modeling:
  train_pipeline:
    setup_mlflow: False   # Do not set as True unless you have mlflow setup
    mlflow_autolog: False # Do not set as True unless you have mlflow setup
    mlflow_tracking_uri: "http://10.51.252.217:5005" 
    mlflow_exp_name: "lstm-big-sweep"
    mlflow_artifact_location: "gs://anomaly-predictor-artifacts/mlflow-tracking-server"
    processed_dir: "/polyaxon-v1-data/data/processed/20220520_095038" # No changes required, will be overwritten during pipeline
    model_name: "LSTMAE"            # Do not change unless you have added a new model type
    model_dir: "/home/abb/models"   # Do not change     
    conf_dir: "/home/abb/conf"      # Do not change

  mlflow_tags:
    hptuning_tag: "LSTM Detection model with big sweep params"
    estimator_name: "LSTMAE"
    estimator_class: "torch.LSTMAE"

  col_names:
    label_column: "Anomaly"
    time_col: "MEASUREMENT_TAKEN_ON(UTC)"

  use_individual_scaler: True

  data_loader:
    init:
      lookback_period: 336
      lookahead_period: 0
      batch_size: 336
      pin_memory: True
      num_workers: 3
      statistical_window: 0
    feature_to_standardize: [
      "Output Power",
      "Overall Vibration",
      "Peak to Peak (X)",
      "Peak to Peak (Y)",
      "Peak to Peak (Z)",
      "Skin Temperature",
      "Speed",
      "Motor Supply Frequency",
      "Vibration (Axial)",
      "Vibration (Radial)",
      "Vibration (Tangential)",
      "Acceleration RMS (Axial)",
      "Acceleration RMS (Radial)",
      "Acceleration RMS (Tangential)",
      "Bearing Condition"
    ]
    shuffle: False
    robust_scaler:
      with_centering: True,
      with_scaling: True,
      copy: True,
      quantile_range: [25.0, 75.0]
      unit_variance: False

  isolation_forest:
    max_features: 1
    max_samples: "auto"
    n_estimators: 2
    random_state: 42

  lstmae:
    model_params:
      hidden_size: [[64, 32], [32, 64]]
      n_layers: [2, 2]
      dropout: 0
    lr: 0.001
    reconstruction_error_mode: "last_timepoint"
    pred_threshold: 
    max_reconstruction_error: 10
    early_stopping_params:
      patience: 70
      min_delta: 0
      path: "checkpoint.pt"

  lstmae_training:
    n_epochs: 1

  pred_threshold_search:
    max_fpr: 0.2
    terminating_recall: 0.4
    default_pred_threshold: 0.5

  evaluation:
    to_run: True
    columns: ["Asset_Name","Pointwise_Recall","Pointwise_F1_Score","Pointwise_FPR", "Overlap_Recall","Overlap_F1_Score","Overlap_FPR"]
    create_visualization: True
    create_encoder_output_tsne: False
    plotting_features: ["Motor Supply Frequency",
      "Vibration (Axial)",
      "Vibration (Radial)",
      "Vibration (Tangential)",
      "Acceleration RMS (Axial)",
      "Acceleration RMS (Radial)",
      "Acceleration RMS (Tangential)",
      "Peak to Peak (X)",
      "Peak to Peak (Y)",
      "Peak to Peak (Z)",
    ]

  visualization_args: 
    Pointwise_F1_Score:
      top_n_assets: 5
      bottom_n_assets: 5
    Pointwise_Recall:
      top_n_assets: 5
      bottom_n_assets: 5
    Pointwise_FPR:
      top_n_assets: 5
      bottom_n_assets: 5
    Overlap_F1_Score:
      top_n_assets: 5
      bottom_n_assets: 5
    Overlap_Recall:
      top_n_assets: 5
      bottom_n_assets: 5
    Overlap_FPR:
      top_n_assets: 5
      bottom_n_assets: 5